#ICEI-PUC-Minas-PMGES-TI/pmg-es-2026-1-ti2-3740100-frametech#49spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
#spring.datasource.username=postgres.aokvawrxhqaroonehrkk
#spring.datasource.password=FrameTech1220
#spring.datasource.driver-class-name=org.postgresql.Driver

# Esta configuração garante que o Hibernate não tente recriar suas tabelas
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.aokvawrxhqaroonehrkk
spring.datasource.password=FrameTech1220
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.auto-commit=false

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true