spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.aokvawrxhqaroonehrkk
spring.datasource.password=FrameTech1220
spring.datasource.driver-class-name=org.postgresql.Driver

# Esta configuração garante que o Hibernate não tente recriar suas tabelas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect